services:
  sequencer:
    environment:
      JAVA_OPTS: -XX:+UnlockExperimentalVMOptions -XX:-UseG1GC -XX:+UseZGC
    depends_on:
      linea-besu-sequencer-plugin-downloader:
        condition: service_completed_successfully
    user: root
    entrypoint:
      - /bin/bash
      - -c
      - |
        sed -e 's/ADD .*=.*/ADD = 4096 # reduced it for rejected tx testing/' /var/lib/besu/traces-limits.toml > /var/lib/besu/traces-limits-reduced.toml
        /opt/besu/bin/besu \
        --config-file=/var/lib/besu/sequencer.config.toml \
        --node-private-key-file="/var/lib/besu/key" \
        --plugin-linea-rejected-tx-endpoint="http://transaction-exclusion-api:8080" \
        --plugin-linea-node-type="SEQUENCER" \
        --plugin-linea-module-limit-file-path="/var/lib/besu/traces-limits-reduced.toml"
  
  l2-node-besu:
    hostname: l2-node-besu
    container_name: l2-node-besu
    image: consensys/linea-besu:24.10-delivery34
    profiles: [ "l2", "l2-bc", "debug" ]
    depends_on:
      linea-besu-sequencer-plugin-downloader:
        condition: service_completed_successfully
      sequencer:
        condition: service_healthy
    user: root
    ports:
      - "9045:8545"
      - "9046:8546"
      - "9050:8550"
      - "9051:8548"
      - "30309:30303"
    healthcheck:
      test: [ "CMD-SHELL", "bash -c \"[ -f /tmp/pid ]\"" ]
      interval: 1s
      timeout: 1s
      retries: 120
    restart: "no"
    environment:
      LOG4J_CONFIGURATION_FILE: /var/lib/besu/log4j.xml
    entrypoint:
      - /bin/bash
      - -c
      - |
        sed -e 's/ADD .*=.*/ADD = 4096 # reduced it for rejected tx testing/' /var/lib/besu/traces-limits.toml > /var/lib/besu/traces-limits-reduced.toml
        /opt/besu/bin/besu \
        --config-file=/var/lib/besu/l2-node-besu.config.toml \
        --genesis-file=/var/lib/besu/genesis.json \
        --plugin-linea-rejected-tx-endpoint="http://transaction-exclusion-api:8080" \
        --plugin-linea-node-type="P2P" \
        --plugin-linea-module-limit-file-path="/var/lib/besu/traces-limits-reduced.toml" \
        --bootnodes=enode://14408801a444dafc44afbccce2eb755f902aed3b5743fed787b3c790e021fef28b8c827ed896aa4e8fb46e22bd67c39f994a73768b4b382f8597b0d44370e15d@11.11.11.101:30303
    volumes:
      - ./config/l2-node-besu/l2-node-besu-config.toml:/var/lib/besu/l2-node-besu.config.toml:ro
      - ./config/linea-besu-sequencer/deny-list.txt:/var/lib/besu/deny-list.txt:ro
      - ./config/l2-node-besu/log4j.xml:/var/lib/besu/log4j.xml:ro
      - ./config/linea-local-dev-genesis-PoA-besu.json/:/var/lib/besu/genesis.json:ro
      - ../config/common/traces-limits-besu-v2.toml:/var/lib/besu/traces-limits.toml:ro
      - ../tmp/linea-besu-sequencer/plugins:/opt/besu/plugins/
      - ../tmp/local/:/data/:rw
    networks:
      linea:
        ipv4_address: 11.11.11.119
  
  postman:
    command: ["echo", "forced exit as not needed"]

  coordinator:
    command: ["echo", "forced exit as not needed"]

  linea-besu-sequencer-finalized-tag-updater-plugin-downloader:
    command: ["echo", "forced exit as not needed"]
  
  zkbesu-shomei:
    entrypoint: ["echo", "forced exit as not needed"]

  shomei-plugin-downloader:
    command: ["echo", "forced exit as not needed"]

  shomei:
    entrypoint: ["echo", "forced exit as not needed"]

  shomei-frontend:
    restart: no
    entrypoint: ["echo", "forced exit as not needed"]

  l1-cl-node:
    entrypoint: ["echo", "forced exit as not needed"]
